apiVersion: v1
kind: ServiceAccount
metadata:
  name: moonlight
  namespace: ms-moonlight
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moonlight
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - watch
      - list
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - watch
      - list
      - create
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - 'apps'
      - 'extensions'
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - 'autoscaling'
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - 'networking.k8s.io'
    resources:
      - ingresses
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moonlight
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: moonlight
subjects:
  - kind: ServiceAccount
    name: moonlight
    namespace: ms-moonlight
