app:
  baseUrl: https://moonlight.limbo.work
  analytics:
    ga:
      trackingId: '' # não remover!!! Se remover isso as métricas ga4 para
    ga4:
      measurementId: G-XKGDLESVHC
      identity: optional

events:
  modules:
    github:
      webhookSecret: ${MOONLIGHT_WEBHOOK_SECRET}
    awsSqs:
      queueUrl: ${MOONLIGHT_WEBHOOK_QUEUE_URL}
      region: ${MOONLIGHT_WEBHOOK_QUEUE_REGION}

apis:
  metrics: http://katchau-accelerate-metrics.ppay.me

backend:
  csp:
    img-src: ["'self'", 'http:', 'https:', 'data:']
  baseUrl: https://moonlight.limbo.work
  cors:
    origin: https://moonlight.limbo.work
  cache:
    store: redis
    connection: ${MOONLIGHT_REDIS}

auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: ${AUTH_MICROSOFT_CLIENT_ID}
        clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
        tenantId: ${AUTH_MICROSOFT_TENANT_ID}
    guest: null

catalog:
  processingInterval:
    hours: ${PROCESSING_INTERVAL_HOURS}
    minutes: ${PROCESSING_INTERVAL_MINUTES}
  orphanStrategy: delete
  rules:
    - allow:
        [
          Component,
          API,
          Resource,
          Group,
          User,
          Template,
          System,
          Domain,
          Location,
        ]
  locations:
    - type: url
      target: https://github.com/PicPay/moonlight-templates/blob/main/template.yaml
      rules:
        - allow: [Template]
  providers:
    github:
      catalogs:
        organization: 'PicPay'
        catalogPath: '/catalog-info.yaml'
        rules:
          - allow:
              [Component, API, Resource, Group, User, System, Domain, Location]

integrations:
  github:
    - host: github.com
      apps:
        $include: github-apps-prod.yaml

techdocs:
  builder: 'external'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${MOONLIGHT_TECH_DOCS_BUCKET}
      region: ${MOONLIGHT_TECH_DOCS_BUCKET_REGION}
      credentials:
        roleArn: ${MOONLIGHT_TECH_DOCS_ROLE_ARN}
  cache:
    ttl: ${REDIS_TTL}
    readTimeout: ${REDIS_TIMEOUT}

fausthanos:
  url: ${FAUSTHANOS_ENDPOINT}
  apiPrefix: ${FAUSTHANOS_PREFIX}
  token: ${FAUSTHANOS_TOKEN}

houston:
  url: ${HOUSTON_ENDPOINT}
  appId: ${HOUSTON_APP_ID}
  squadName: ${HOUSTON_SQUAD_NAME}

vision:
  url: ${VISION_ENDPOINT}

announcements:
  githubIntegration: true

githubRepositorySetting:
  canEdit: true
