apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: moonlight-frontend
  labels:
    moonlight.picpay/language: javascript
    moonlight.picpay/framework: reactjs
    moonlight.picpay/monitoring: dynatrace
  tags:
    - postgres
    - react
    - typescript
    - nodejs
    - backstage
  description: |
    Moonlight Portal é o Front-End da IDP do PicPay
  links:
    - title: Backstage
      url: http://backstage.io
    - title: Backstage Documentation
      url: https://backstage.io/docs
    - title: Backstage Storybook
      url: https://backstage.io/storybook
    - title: Backstage Discord Channel
      url: https://discord.com/invite/EBHEGzX
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: PicPay/picpay-ops-ms-moonlight/packages/app
    sonarqube.org/project-key: PicPay_picpay-ops-moonlight
    lighthouse.com/website-url: https://backstage.io
spec:
  lifecycle: production
  owner: squad-atlantis
  system: moonlight
  type: web
  dependsOn:
    - component:default/ms-moonlight
