apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: moonlight-template-additional-group-information
  title: Configure a group
  links:
    - icon: help
      url: https://picpay.enterprise.slack.com/archives/C02K6H1JBT2
      title: Support
  tags:
    - moonlight
    - picpay-entity-provider
  description: |
    Template for updating group information

spec:
  image: ./assets/network.png
  owner: squad-atlantis
  type: blueprint

  parameters:
    - title: Group identification
      properties:
        identifier:
          type: string
          title: Group
          description: Group
          ui:field: ComponentPicker
          ui:options:
            useLabel: spec.profile.displayName
            catalogFilter:
              - kind: Group
            defaultKind: Group
            allowArbitraryValues: false


    - title: Additional Information
      properties:
        groupType:
          title: Type
          type: string
          default: squad
          enumNames:
            - Organization
            - VP
            - Business unit
            - Cost center
            - Tribe
            - Squad
          enum:
            - organization
            - vp
            - business-unit
            - cost-center
            - tribe
            - squad

        name:
          title: New Group Name
          type: string
          minLength: 3
          maxLength: 50
          pattern: '^[a-z|0-9|-]*(?<!-)$'
          description: |
            Just put the name of your group, for example: my-group-name;
            Name of the kebab-case model component;
            Write a minimum of 3 characters and a maximum of 50;
            Lowercase letters only;
            Do not use accents;
            Separate words by hyphen;

        displayName:
          title: Display Name
          type: string
          minLength: 3
          maxLength: 128
          description: |
            Just put the name of your group, for example: My Group Name;
            Name of the model component;
            Write a minimum of 3 characters and a maximum of 128;
            Use uppercase and lowercase letters;

        description:
          title: Description
          type: string

        picture:
          title: Picture
          type: string
          description: Public URL of the group picture

  steps:
    - id: save-group-information
      name: Save group information
      action: moonlight:http-request
      input:
        url: http://localhost:7001/api/entity-provider/additional-information
        method: POST
        headers:
          Content-Type: application/json
        body:
          identifier: '${{ parameters.identifier }}'
          name: '${{ parameters.name }}'
          displayName: '${{ parameters.displayName }}'
          description: '${{ parameters.description }}'
          type: '${{ parameters.groupType }}'
          picture: '${{ parameters.picture }}'
        throwOutput: true
        printResultAfter: true