basePath: /
definitions:
  models.ResponseList:
    properties:
      data:
        items: {}
        type: array
      has_next_page:
        type: boolean
      limit:
        type: integer
    type: object
  viewmodel.ComponentDeletionResponse:
    properties:
      created_at:
        type: string
      deletion: {}
      id:
        type: string
      name:
        type: string
      owner:
        type: string
      reason:
        type: string
      recover: {}
      renaming: {}
      request_type:
        type: string
      requestedBy:
        type: string
      reviewers:
        items: {}
        type: array
      status:
        type: string
      updated_at:
        type: string
    type: object
host: fausthanos.ms.qa
info:
  contact:
    name: '#moonlight on Slack'
    url: https://moonlight.limbo.work/
  description: Responsible for completely erasing a service
  termsOfService: http://swagger.io/terms/
  title: Fausthanos
  version: '1.0'
paths:
  /api/v1/component:
    get:
      consumes:
        - '*/*'
      description: Returns a single request following name on parameter
      parameters:
        - description: Name of the Component/Moonlight Entity
          in: body
          name: name
          schema:
            type: primitive
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
      summary: Returns a single request
      tags:
        - root
    post:
      consumes:
        - '*/*'
      description: Inserts a new request to the database
      parameters:
        - description: Name of the Component/Moonlight Entity
          in: body
          name: name
          schema:
            type: primitive
        - description: Who  made the request
          in: body
          name: requestedBy
          schema:
            type: primitive
        - description:
            id of the request when operation is rename or id of previous
            request when operation is rollback
          in: body
          name: id
          schema:
            type: primitive
        - description: operation requested
          enum:
            - delete
            - rename
            - rollback
          in: body
          name: operation
          schema:
            type: primitive
        - description: The reason that the user included on the request
          in: body
          name: reason
          schema:
            type: primitive
        - description: List of the reviewers
          in: body
          name: reviewers
          schema:
            items:
              type: string
            type: array
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/viewmodel.ComponentDeletionResponse'
      summary: Saves a request into the database
      tags:
        - root
    put:
      consumes:
        - '*/*'
      description: Updates a request already saved to fausthanos
      parameters:
        - description: Name of the Component/Moonlight Entity
          in: body
          name: name
          schema:
            type: primitive
        - description: New Reviewer SSO Email
          in: body
          name: reviewer
          schema:
            type: primitive
        - description: Reviewer approvation status (APPROVED | REJECTED)
          in: body
          name: review_status
          schema:
            type: primitive
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
      summary: Updates a request from database
      tags:
        - root
  /api/v1/component/:id/retry:
    post:
      consumes:
        - '*/*'
      description: Inserts a new request to the database
      parameters:
        - description: id of the request
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: string
      summary: Saves a request into the database
      tags:
        - root
  /api/v1/components:
    get:
      consumes:
        - '*/*'
      description: List of all requests inside fausthanos.
      parameters:
        - description: Name of the Component/Moonlight Entity
          in: query
          name: name
          type: string
        - description: Who  made the request
          in: query
          name: requestedBy
          type: string
        - description: The reason that the user included on the request
          in: query
          name: reason
          type: string
        - description: Status of the request
          in: query
          name: status
          type: string
        - description: Time of last update on document
          in: query
          name: updated_at
          type: string
        - description: Time of last update on document
          in: query
          name: created_at
          type: string
        - description: Pagination, starts with 1
          in: query
          name: page
          type: integer
        - description: Limit - 1 to 100
          in: query
          name: limit
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseList'
      summary: Returns all requests made by PicPayLovers.
      tags:
        - root
  /health:
    get:
      consumes:
        - '*/*'
      description: get the status of server.
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
        - root
swagger: '2.0'
