export enum Status {
  COMPONENT_NOT_FOUND = 'COMPONENT_NOT_FOUND',
  GROUP_OWNER_NOT_FOUND = 'GROUP_OWNER_NOT_FOUND',
  REVIEWERS_NOT_FOUND = 'REVIEWERS_NOT_FOUND',
  FAILED_GET_REVIEWERS = 'FAILED_GET_REVIEWERS',
  FAILED_GET_OWNER = 'FAILED_GET_OWNER',
}
